# Generated by Django 3.0.2 on 2020-01-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Строительная компания')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Строительная компания',
                'verbose_name_plural': 'Строительные компании',
                'db_table': 'tbl_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Район')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'db_table': 'tbl_districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Этап строительства')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
                'db_table': 'tbl_stages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название ЖК')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('completion', models.IntegerField(verbose_name='Год завершения строительства')),
                ('price', models.IntegerField(verbose_name='Стоимость квадратного метра')),
                ('cost', models.IntegerField(verbose_name='Цена квартиры')),
                ('square', models.IntegerField(verbose_name='Площадь')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_owner', to='flats.Company', verbose_name='Строительная компания')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_district', to='flats.District', verbose_name='Район')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_stage', to='flats.Stage', verbose_name='Этап строительства')),
            ],
            options={
                'verbose_name': 'ЖК',
                'verbose_name_plural': 'ЖК',
                'db_table': 'tbl_houses',
                'ordering': ['name'],
            },
        ),
    ]
