# Generated by Django 3.0.2 on 2020-01-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_owner', to='flats.Company', verbose_name='Строительная компания'),
        ),
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_district', to='flats.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='house',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_stage', to='flats.Stage', verbose_name='Этап строительства'),
        ),
    ]
