# Generated by Django 3.0.2 on 2020-01-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20200123_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.RemoveField(
            model_name='house',
            name='square',
        ),
    ]
