# Generated by Django 3.0.2 on 2020-01-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20200123_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('price', models.IntegerField(verbose_name='Стоимость квадратного метра')),
                ('cost', models.IntegerField(verbose_name='Цена квартиры')),
                ('square', models.IntegerField(verbose_name='Площадь')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_house', to='flats.House', verbose_name='ЖК')),
            ],
        ),
    ]
