# Generated by Django 3.0.2 on 2020-01-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_apartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['name'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='tbl_appartments',
        ),
    ]
