# Generated by Django 3.0.2 on 2020-01-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_auto_20200124_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='hirepurchase',
            field=models.BooleanField(default=0, verbose_name='Рассрочка'),
        ),
        migrations.AddField(
            model_name='house',
            name='maternalcapital',
            field=models.BooleanField(default=0, verbose_name='Материнский капитал'),
        ),
        migrations.AddField(
            model_name='house',
            name='mortgage',
            field=models.BooleanField(default=0, verbose_name='Ипотека'),
        ),
    ]
