# Generated by Django 3.0.2 on 2020-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_auto_20200124_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='difference',
            field=models.BooleanField(default=0, verbose_name='Стоимость квартиры зависит от этажа'),
        ),
    ]
