# Generated by Django 3.0.2 on 2020-01-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_apartment_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='difference',
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='tbl_apartments',
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('price', models.IntegerField(verbose_name='Стоимость квадратного метра')),
                ('cost', models.IntegerField(verbose_name='Цена квартиры')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_apartment', to='flats.Apartment', verbose_name='Квартира')),
            ],
        ),
    ]
