# Generated by Django 3.0.2 on 2020-01-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0008_auto_20200124_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['apartment'], 'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelTable(
            name='floor',
            table='tbl_floors',
        ),
    ]
