# Generated by Django 3.0.2 on 2020-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0009_auto_20200124_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена квартиры'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость квадратного метра'),
        ),
    ]
