# Generated by Django 3.0.2 on 2020-01-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0011_house_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['rooms'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['floor'], 'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
    ]
