# Generated by Django 3.0.2 on 2020-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0012_auto_20200125_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
