# Generated by Django 3.0.2 on 2020-01-31 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flats', '0013_house_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_author', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='cost',
            field=models.IntegerField(verbose_name='Минимальная цена квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(verbose_name='Минимальная стоимость квадратного метра'),
        ),
    ]
